<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../VerifyCurrentHouseHoldIncomeFedProxyService.wsdl"/>
      <rootElement name="CurrentIncomeResponse" namespace="http://vci.dsh.cms.gov/exchange/1.0"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../VerifyCurrentHouseHoldIncomeFedProxyService.wsdl"/>
      <rootElement name="CurrentIncomeResponse" namespace="http://vci.dsh.cms.gov/exchange/1.0"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE NOV 08 15:16:39 EST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                xmlns:ns0="http://hix.cms.gov/0.1/hix-core"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://niem.gov/niem/niem-core/2.0"
                xmlns:ns4="http://niem.gov/niem/appinfo/2.1"
                xmlns:ns6="http://niem.gov/niem/appinfo/2.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns1="http://niem.gov/niem/structures/2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns5="http://niem.gov/niem/usps_states/2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:exch="http://vci.dsh.cms.gov/exchange/1.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns3="http://vci.dsh.cms.gov/extension/1.0"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ns7="http://niem.gov/niem/proxy/xsd/2.0"
                exclude-result-prefixes="xsl xsi wsp ns0 xsd ns2 ns4 ns6 ns1 ns5 WL5G3N3 wsdl exch ns3 ns7 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <exch:CurrentIncomeResponse>
      <xsl:if test="/exch:CurrentIncomeResponse/@ns1:id">
        <xsl:attribute name="ns1:id">
          <xsl:value-of select="/exch:CurrentIncomeResponse/@ns1:id"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/exch:CurrentIncomeResponse/@ns1:metadata">
        <xsl:attribute name="ns1:metadata">
          <xsl:value-of select="/exch:CurrentIncomeResponse/@ns1:metadata"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/exch:CurrentIncomeResponse/@ns1:linkMetadata">
        <xsl:attribute name="ns1:linkMetadata">
          <xsl:value-of select="/exch:CurrentIncomeResponse/@ns1:linkMetadata"/>
        </xsl:attribute>
      </xsl:if>
      <ns3:ResponseMetadata>
        <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/@ns1:id">
          <xsl:attribute name="ns1:id">
            <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/@ns1:id"/>
          </xsl:attribute>
        </xsl:if>
        <ns0:ResponseCode>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:id">
            <xsl:attribute name="ns1:id">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:id"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:metadata">
            <xsl:attribute name="ns1:metadata">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:metadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:linkMetadata">
            <xsl:attribute name="ns1:linkMetadata">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode/@ns1:linkMetadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseCode"/>
        </ns0:ResponseCode>
        <ns0:ResponseDescriptionText>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:id">
            <xsl:attribute name="ns1:id">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:id"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:metadata">
            <xsl:attribute name="ns1:metadata">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:metadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:linkMetadata">
            <xsl:attribute name="ns1:linkMetadata">
              <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:linkMetadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:ResponseDescriptionText"/>
        </ns0:ResponseDescriptionText>
        <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText">
          <ns0:TDSResponseDescriptionText>
            <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:id">
              <xsl:attribute name="ns1:id">
                <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:metadata">
              <xsl:attribute name="ns1:metadata">
                <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:linkMetadata">
              <xsl:attribute name="ns1:linkMetadata">
                <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/exch:CurrentIncomeResponse/ns3:ResponseMetadata/ns0:TDSResponseDescriptionText"/>
          </ns0:TDSResponseDescriptionText>
        </xsl:if>
      </ns3:ResponseMetadata>
      <xsl:for-each select="/exch:CurrentIncomeResponse/ns3:ResponseInformation">
        <ns3:ResponseInformation>
          <xsl:if test="@ns1:id">
            <xsl:attribute name="ns1:id">
              <xsl:value-of select="@ns1:id"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns1:metadata">
            <xsl:attribute name="ns1:metadata">
              <xsl:value-of select="@ns1:metadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns1:linkMetadata">
            <xsl:attribute name="ns1:linkMetadata">
              <xsl:value-of select="@ns1:linkMetadata"/>
            </xsl:attribute>
          </xsl:if>
          <ns3:ResponseMetadata>
            <xsl:if test="ns3:ResponseMetadata/@ns1:id">
              <xsl:attribute name="ns1:id">
                <xsl:value-of select="ns3:ResponseMetadata/@ns1:id"/>
              </xsl:attribute>
            </xsl:if>
            <ns0:ResponseCode>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:id">
                <xsl:attribute name="ns1:id">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:metadata">
                <xsl:attribute name="ns1:metadata">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:linkMetadata">
                <xsl:attribute name="ns1:linkMetadata">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseCode/@ns1:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseCode"/>
            </ns0:ResponseCode>
            <ns0:ResponseDescriptionText>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:id">
                <xsl:attribute name="ns1:id">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:metadata">
                <xsl:attribute name="ns1:metadata">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:linkMetadata">
                <xsl:attribute name="ns1:linkMetadata">
                  <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseDescriptionText/@ns1:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns3:ResponseMetadata/ns0:ResponseDescriptionText"/>
            </ns0:ResponseDescriptionText>
            <xsl:if test="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText">
              <ns0:TDSResponseDescriptionText>
                <xsl:if test="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns3:ResponseMetadata/ns0:TDSResponseDescriptionText"/>
              </ns0:TDSResponseDescriptionText>
            </xsl:if>
          </ns3:ResponseMetadata>
          <xsl:if test="ns3:EmployeeInformation">
            <ns3:EmployeeInformation>
              <xsl:if test="ns3:EmployeeInformation/@ns1:id">
                <xsl:attribute name="ns1:id">
                  <xsl:value-of select="ns3:EmployeeInformation/@ns1:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:EmployeeInformation/@ns1:metadata">
                <xsl:attribute name="ns1:metadata">
                  <xsl:value-of select="ns3:EmployeeInformation/@ns1:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns3:EmployeeInformation/@ns1:linkMetadata">
                <xsl:attribute name="ns1:linkMetadata">
                  <xsl:value-of select="ns3:EmployeeInformation/@ns1:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <ns2:PersonBirthDate>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
              </ns2:PersonBirthDate>
              <ns2:PersonName>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns2:PersonGivenName>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName"/>
                </ns2:PersonGivenName>
                <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName">
                  <ns2:PersonMiddleName>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName"/>
                  </ns2:PersonMiddleName>
                </xsl:if>
                <ns2:PersonSurName>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName"/>
                </ns2:PersonSurName>
              </ns2:PersonName>
              <ns2:PersonSSNIdentification>
                <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonSSNIdentification"/>
              </ns2:PersonSSNIdentification>
            </ns3:EmployeeInformation>
          </xsl:if>
          <xsl:for-each select="ns3:CurrentIncomeInformation">
            <ns3:CurrentIncomeInformation>
              <xsl:if test="@ns1:id">
                <xsl:attribute name="ns1:id">
                  <xsl:value-of select="@ns1:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@ns1:metadata">
                <xsl:attribute name="ns1:metadata">
                  <xsl:value-of select="@ns1:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@ns1:linkMetadata">
                <xsl:attribute name="ns1:linkMetadata">
                  <xsl:value-of select="@ns1:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <ns3:Tier>
                <xsl:value-of select="ns3:Tier"/>
              </ns3:Tier>
              <ns3:AsOfDate>
                <xsl:if test="ns3:AsOfDate/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:AsOfDate/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:AsOfDate/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:AsOfDate/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:AsOfDate/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:AsOfDate/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns2:Date>
                  <xsl:if test="ns3:AsOfDate/ns2:Date/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:AsOfDate/ns2:Date/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:AsOfDate/ns2:Date/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:AsOfDate/ns2:Date/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:AsOfDate/ns2:Date/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:AsOfDate/ns2:Date/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:AsOfDate/ns2:Date"/>
                </ns2:Date>
              </ns3:AsOfDate>
              <ns3:VerificationMetadata>
                <xsl:if test="ns3:VerificationMetadata/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:VerificationMetadata/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <ns0:VerificationID>
                  <xsl:if test="ns3:VerificationMetadata/ns0:VerificationID/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:VerificationMetadata/ns0:VerificationID/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:VerificationMetadata/ns0:VerificationID/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:VerificationMetadata/ns0:VerificationID/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:VerificationMetadata/ns0:VerificationID/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:VerificationMetadata/ns0:VerificationID/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:VerificationMetadata/ns0:VerificationID"/>
                </ns0:VerificationID>
              </ns3:VerificationMetadata>
              <ns3:EmployeeInformation>
                <xsl:if test="ns3:EmployeeInformation/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:EmployeeInformation/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:EmployeeInformation/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployeeInformation/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:EmployeeInformation/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns2:PersonBirthDate>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonBirthDate/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                </ns2:PersonBirthDate>
                <ns2:PersonName>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns2:PersonGivenName>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonGivenName"/>
                  </ns2:PersonGivenName>
                  <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName">
                    <ns2:PersonMiddleName>
                      <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonMiddleName"/>
                    </ns2:PersonMiddleName>
                  </xsl:if>
                  <ns2:PersonSurName>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonName/ns2:PersonSurName"/>
                  </ns2:PersonSurName>
                </ns2:PersonName>
                <ns2:PersonSSNIdentification>
                  <xsl:value-of select="ns3:EmployeeInformation/ns2:PersonSSNIdentification"/>
                </ns2:PersonSSNIdentification>
              </ns3:EmployeeInformation>
              <ns3:EmployerInformation>
                <xsl:if test="ns3:EmployerInformation/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:EmployerInformation/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployerInformation/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:EmployerInformation/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmployerInformation/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:EmployerInformation/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns3:EmployerOrganization>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns2:OrganizationIdentification>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <ns2:IdentificationID>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationIdentification/ns2:IdentificationID"/>
                    </ns2:IdentificationID>
                  </ns2:OrganizationIdentification>
                  <ns2:OrganizationName>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerOrganization/ns2:OrganizationName"/>
                  </ns2:OrganizationName>
                </ns3:EmployerOrganization>
                <ns3:EmployerAddress>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns2:LocationStreet>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText">
                      <ns2:StreetFullText>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetFullText"/>
                      </ns2:StreetFullText>
                    </xsl:if>
                    <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText">
                      <ns2:StreetExtensionText>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStreet/ns2:StreetExtensionText"/>
                      </ns2:StreetExtensionText>
                    </xsl:if>
                  </ns2:LocationStreet>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName">
                    <ns2:LocationCityName>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationCityName"/>
                    </ns2:LocationCityName>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode">
                    <ns2:LocationStateUSPostalServiceCode>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationStateUSPostalServiceCode"/>
                    </ns2:LocationStateUSPostalServiceCode>
                  </xsl:if>
                  <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode">
                    <ns2:LocationPostalCode>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:EmployerInformation/ns3:EmployerAddress/ns2:LocationPostalCode"/>
                    </ns2:LocationPostalCode>
                  </xsl:if>
                </ns3:EmployerAddress>
              </ns3:EmployerInformation>
              <ns3:EmploymentInformation>
                <xsl:if test="ns3:EmploymentInformation/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:EmploymentInformation/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmploymentInformation/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:EmploymentInformation/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:EmploymentInformation/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:EmploymentInformation/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns3:EmployeeStatusCode>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusCode/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusCode"/>
                </ns3:EmployeeStatusCode>
                <ns3:EmployeeStatusMessage>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusMessage/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns3:EmploymentInformation/ns3:EmployeeStatusMessage"/>
                </ns3:EmployeeStatusMessage>
                <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation">
                  <ns3:PersonEmploymentAssociation>
                    <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate">
                      <ns0:EmploymentOriginalHireDate>
                        <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:EmploymentInformation/ns3:PersonEmploymentAssociation/ns0:EmploymentOriginalHireDate/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                      </ns0:EmploymentOriginalHireDate>
                    </xsl:if>
                  </ns3:PersonEmploymentAssociation>
                </xsl:if>
              </ns3:EmploymentInformation>
              <ns3:BaseCompensationInformation>
                <xsl:if test="ns3:BaseCompensationInformation/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:BaseCompensationInformation/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:BaseCompensationInformation/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:BaseCompensationInformation/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <ns3:PayRate>
                  <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount">
                    <ns0:IncomeAmount>
                      <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayRate/ns0:IncomeAmount"/>
                    </ns0:IncomeAmount>
                  </xsl:if>
                </ns3:PayRate>
                <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyCode">
                  <ns3:PayFrequencyCode>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyCode/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyCode"/>
                  </ns3:PayFrequencyCode>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage">
                  <ns3:PayFrequencyMessage>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayFrequencyMessage"/>
                  </ns3:PayFrequencyMessage>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode">
                  <ns3:PayPeriodFrequencyCode>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyCode"/>
                  </ns3:PayPeriodFrequencyCode>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage">
                  <ns3:PayPeriodFrequencyMessage>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:BaseCompensationInformation/ns3:PayPeriodFrequencyMessage"/>
                  </ns3:PayPeriodFrequencyMessage>
                </xsl:if>
                <xsl:if test="ns3:BaseCompensationInformation/ns3:AnnualizedIncome">
                  <ns3:AnnualizedIncome>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="ns3:BaseCompensationInformation/ns3:AnnualizedIncome/@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns3:BaseCompensationInformation/ns3:AnnualizedIncome"/>
                  </ns3:AnnualizedIncome>
                </xsl:if>
              </ns3:BaseCompensationInformation>
              <xsl:if test="ns3:AnnualCompensation">
                <ns3:AnnualCompensation>
                  <xsl:if test="ns3:AnnualCompensation/@ns1:id">
                    <xsl:attribute name="ns1:id">
                      <xsl:value-of select="ns3:AnnualCompensation/@ns1:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:AnnualCompensation/@ns1:metadata">
                    <xsl:attribute name="ns1:metadata">
                      <xsl:value-of select="ns3:AnnualCompensation/@ns1:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns3:AnnualCompensation/@ns1:linkMetadata">
                    <xsl:attribute name="ns1:linkMetadata">
                      <xsl:value-of select="ns3:AnnualCompensation/@ns1:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:for-each select="ns3:AnnualCompensation/ns3:AnnualCompensationInformation">
                    <ns3:AnnualCompensationInformation>
                      <xsl:if test="@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:IncomeYear">
                        <ns3:IncomeYear>
                          <xsl:if test="ns3:IncomeYear/@ns1:id">
                            <xsl:attribute name="ns1:id">
                              <xsl:value-of select="ns3:IncomeYear/@ns1:id"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeYear/@ns1:metadata">
                            <xsl:attribute name="ns1:metadata">
                              <xsl:value-of select="ns3:IncomeYear/@ns1:metadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeYear/@ns1:linkMetadata">
                            <xsl:attribute name="ns1:linkMetadata">
                              <xsl:value-of select="ns3:IncomeYear/@ns1:linkMetadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <ns2:Year>
                            <xsl:if test="ns3:IncomeYear/ns2:Year/@ns1:id">
                              <xsl:attribute name="ns1:id">
                                <xsl:value-of select="ns3:IncomeYear/ns2:Year/@ns1:id"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:if test="ns3:IncomeYear/ns2:Year/@ns1:metadata">
                              <xsl:attribute name="ns1:metadata">
                                <xsl:value-of select="ns3:IncomeYear/ns2:Year/@ns1:metadata"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:if test="ns3:IncomeYear/ns2:Year/@ns1:linkMetadata">
                              <xsl:attribute name="ns1:linkMetadata">
                                <xsl:value-of select="ns3:IncomeYear/ns2:Year/@ns1:linkMetadata"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns3:IncomeYear/ns2:Year"/>
                          </ns2:Year>
                        </ns3:IncomeYear>
                      </xsl:if>
                      <xsl:if test="ns3:BaseCompensation">
                        <ns3:BaseCompensation>
                          <xsl:if test="ns3:BaseCompensation/@ns1:id">
                            <xsl:attribute name="ns1:id">
                              <xsl:value-of select="ns3:BaseCompensation/@ns1:id"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:BaseCompensation/@ns1:metadata">
                            <xsl:attribute name="ns1:metadata">
                              <xsl:value-of select="ns3:BaseCompensation/@ns1:metadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:BaseCompensation/@ns1:linkMetadata">
                            <xsl:attribute name="ns1:linkMetadata">
                              <xsl:value-of select="ns3:BaseCompensation/@ns1:linkMetadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns3:BaseCompensation"/>
                        </ns3:BaseCompensation>
                      </xsl:if>
                      <xsl:if test="ns3:TotalCompensation">
                        <ns3:TotalCompensation>
                          <xsl:if test="ns3:TotalCompensation/@ns1:id">
                            <xsl:attribute name="ns1:id">
                              <xsl:value-of select="ns3:TotalCompensation/@ns1:id"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:TotalCompensation/@ns1:metadata">
                            <xsl:attribute name="ns1:metadata">
                              <xsl:value-of select="ns3:TotalCompensation/@ns1:metadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:TotalCompensation/@ns1:linkMetadata">
                            <xsl:attribute name="ns1:linkMetadata">
                              <xsl:value-of select="ns3:TotalCompensation/@ns1:linkMetadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns3:TotalCompensation"/>
                        </ns3:TotalCompensation>
                      </xsl:if>
                    </ns3:AnnualCompensationInformation>
                  </xsl:for-each>
                </ns3:AnnualCompensation>
              </xsl:if>
              <ns3:PayPeriod>
                <xsl:if test="ns3:PayPeriod/@ns1:id">
                  <xsl:attribute name="ns1:id">
                    <xsl:value-of select="ns3:PayPeriod/@ns1:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:PayPeriod/@ns1:metadata">
                  <xsl:attribute name="ns1:metadata">
                    <xsl:value-of select="ns3:PayPeriod/@ns1:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns3:PayPeriod/@ns1:linkMetadata">
                  <xsl:attribute name="ns1:linkMetadata">
                    <xsl:value-of select="ns3:PayPeriod/@ns1:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:for-each select="ns3:PayPeriod/ns3:PayPeriodInformation">
                  <ns3:PayPeriodInformation>
                    <xsl:if test="@ns1:id">
                      <xsl:attribute name="ns1:id">
                        <xsl:value-of select="@ns1:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="@ns1:metadata">
                      <xsl:attribute name="ns1:metadata">
                        <xsl:value-of select="@ns1:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="@ns1:linkMetadata">
                      <xsl:attribute name="ns1:linkMetadata">
                        <xsl:value-of select="@ns1:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <ns3:PayPeriodEndDate>
                      <xsl:if test="ns3:PayPeriodEndDate/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:PayPeriodEndDate/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:PayPeriodEndDate/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:PayPeriodEndDate/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:PayPeriodEndDate/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:PayPeriodEndDate/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns2:Date>
                        <xsl:if test="ns3:PayPeriodEndDate/ns2:Date/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:PayPeriodEndDate/ns2:Date/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:PayPeriodEndDate/ns2:Date/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:PayPeriodEndDate/ns2:Date/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:PayPeriodEndDate/ns2:Date/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:PayPeriodEndDate/ns2:Date/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns3:PayPeriodEndDate/ns2:Date"/>
                      </ns2:Date>
                    </ns3:PayPeriodEndDate>
                    <ns3:IncomeDetail>
                      <xsl:if test="ns3:IncomeDetail/@ns1:id">
                        <xsl:attribute name="ns1:id">
                          <xsl:value-of select="ns3:IncomeDetail/@ns1:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:IncomeDetail/@ns1:metadata">
                        <xsl:attribute name="ns1:metadata">
                          <xsl:value-of select="ns3:IncomeDetail/@ns1:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns3:IncomeDetail/@ns1:linkMetadata">
                        <xsl:attribute name="ns1:linkMetadata">
                          <xsl:value-of select="ns3:IncomeDetail/@ns1:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeAmount>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeAmount/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeAmount"/>
                      </ns0:IncomeAmount>
                      <xsl:if test="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure">
                        <ns0:IncomeHoursPerWeekMeasure>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:id">
                            <xsl:attribute name="ns1:id">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:id"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:metadata">
                            <xsl:attribute name="ns1:metadata">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:metadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:linkMetadata">
                            <xsl:attribute name="ns1:linkMetadata">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure/@ns1:linkMetadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeHoursPerWeekMeasure"/>
                        </ns0:IncomeHoursPerWeekMeasure>
                      </xsl:if>
                      <ns0:IncomeDate>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeDate/@ns1:id">
                          <xsl:attribute name="ns1:id">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeDate/@ns1:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeDate/@ns1:metadata">
                          <xsl:attribute name="ns1:metadata">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeDate/@ns1:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns3:IncomeDetail/ns0:IncomeDate/@ns1:linkMetadata">
                          <xsl:attribute name="ns1:linkMetadata">
                            <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeDate/@ns1:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                      </ns0:IncomeDate>
                      <xsl:if test="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount">
                        <ns0:IncomeNetPaymentAmount>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:id">
                            <xsl:attribute name="ns1:id">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:id"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:metadata">
                            <xsl:attribute name="ns1:metadata">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:metadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:linkMetadata">
                            <xsl:attribute name="ns1:linkMetadata">
                              <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount/@ns1:linkMetadata"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="ns3:IncomeDetail/ns0:IncomeNetPaymentAmount"/>
                        </ns0:IncomeNetPaymentAmount>
                      </xsl:if>
                    </ns3:IncomeDetail>
                  </ns3:PayPeriodInformation>
                </xsl:for-each>
              </ns3:PayPeriod>
            </ns3:CurrentIncomeInformation>
          </xsl:for-each>
        </ns3:ResponseInformation>
      </xsl:for-each>
      <exch:RequestNumber>
        <xsl:value-of select="/exch:CurrentIncomeResponse/exch:RequestNumber"/>
      </exch:RequestNumber>
    </exch:CurrentIncomeResponse>
  </xsl:template>
</xsl:stylesheet>
