<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeClientEnquryRequest.wsdl"/>
      <rootElement name="ClientInquiryRequest" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/DCAS/ESB/ACEDS/wsdl/DHSDCASWebservices.wsdl"/>
      <rootElement name="DHSDQ500" namespace="urn:com-softwareag-entirex-rpc:EISBATCH"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [TUE NOV 15 13:36:25 EST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenAcedsClientEnquiryService/ConsumeClientEnquryRequest"
                xmlns:ns0="http://namespace.softwareag.com/entirex/xml/mapping"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_APP/HavenClientInquiryACEDSService/ConsumeClientInquiryRequest"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:sn0="urn:com-softwareag-entirex-rpc:EISBATCH"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:snh="urn:com.softwareag.entirex.xml.rt"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi tns xsd plt pc imp1 wsdl jca ns0 sn0 snh soap soap12 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <sn0:DHSDQ500>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-CODE != ""'>
        <_CONDITION-CODE>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-CODE"/>
        </_CONDITION-CODE>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-DESC != ""'>
        <_CONDITION-DESC>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-DESC"/>
        </_CONDITION-DESC>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_USER-ID != ""'>
        <_USER-ID>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_USER-ID"/>
        </_USER-ID>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-NUMBER-I != ""'>
        <_CLIENT-NUMBER-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-NUMBER-I"/>
        </_CLIENT-NUMBER-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_LAST-NAME-I != ""'>
        <_LAST-NAME-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_LAST-NAME-I"/>
        </_LAST-NAME-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_FIRST-NAME-I != ""'>
        <_FIRST-NAME-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_FIRST-NAME-I"/>
        </_FIRST-NAME-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_MIDDLE-NAME-I != ""'>
        <_MIDDLE-NAME-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_MIDDLE-NAME-I"/>
        </_MIDDLE-NAME-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_SUFFIX-I != ""'>
        <_SUFFIX-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SUFFIX-I"/>
        </_SUFFIX-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_DATE-OF-BIRTH-I != ""'>
        <_DATE-OF-BIRTH-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_DATE-OF-BIRTH-I"/>
        </_DATE-OF-BIRTH-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_SEX-I != ""'>
        <_SEX-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SEX-I"/>
        </_SEX-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_SSN-I != ""'>
        <_SSN-I>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SSN-I"/>
        </_SSN-I>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-SHORT-ARRAY-OUT != ""'>
        <_CLIENT-SHORT-ARRAY-OUT>
          <xsl:for-each select="/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-SHORT-ARRAY-OUT/imp1:string">
            <string>
              <xsl:value-of select="."/>
            </string>
          </xsl:for-each>
        </_CLIENT-SHORT-ARRAY-OUT>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CITIZENSHIP-O != ""'>
        <_CITIZENSHIP-O>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CITIZENSHIP-O"/>
        </_CITIZENSHIP-O>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CITIZENSHIP-VERIF-O != ""'>
        <_CITIZENSHIP-VERIF-O>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CITIZENSHIP-VERIF-O"/>
        </_CITIZENSHIP-VERIF-O>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_RACE-O != ""'>
        <_RACE-O>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_RACE-O"/>
        </_RACE-O>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_ETHNIC-CLASS-O != ""'>
        <_ETHNIC-CLASS-O>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_ETHNIC-CLASS-O"/>
        </_ETHNIC-CLASS-O>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-NUMBER-O != ""'>
        <_CLIENT-NUMBER-O>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CLIENT-NUMBER-O"/>
        </_CLIENT-NUMBER-O>
      </xsl:if>
      <xsl:if test='/imp1:ClientInquiryRequest/imp1:ACEDS_MEDICAID-ARRAY != ""'>
        <_MEDICAID-ARRAY>
          <xsl:for-each select="/imp1:ClientInquiryRequest/imp1:ACEDS_MEDICAID-ARRAY/imp1:string">
            <string>
              <xsl:value-of select="."/>
            </string>
          </xsl:for-each>
        </_MEDICAID-ARRAY>
      </xsl:if>
    </sn0:DHSDQ500>
  </xsl:template>
</xsl:stylesheet>
