<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeClientEnquryRequest.wsdl"/>
      <rootElement name="ClientInquiryRequest" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/apps/DCAS/ESB/ACEDS/wsdl/DHSDCASWebservices.wsdl"/>
      <rootElement name="DHSDQ500Response" namespace="urn:com-softwareag-entirex-rpc:EISBATCH"/>
      <param name="InvokeAceds_DHSDQ500_OutputVariable.parameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeClientEnquryRequest.wsdl"/>
      <rootElement name="ClientInquiryResponse" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [TUE NOV 15 13:38:20 EST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenAcedsClientEnquiryService/ConsumeClientEnquryRequest"
                xmlns:ns0="http://namespace.softwareag.com/entirex/xml/mapping"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:sn0="urn:com-softwareag-entirex-rpc:EISBATCH"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:snh="urn:com.softwareag.entirex.xml.rt"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi tns ns0 xsd plt pc sn0 snh soap soap12 imp1 wsdl jca oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="InvokeAceds_DHSDQ500_OutputVariable.parameters"/>
  <xsl:template match="/">
    <imp1:ClientInquiryResponse>
      <xsl:if test="/imp1:ClientInquiryRequest/imp1:RequestNumber">
        <imp1:RequestNumber>
          <xsl:if test="/imp1:ClientInquiryRequest/imp1:RequestNumber/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:RequestNumber/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:RequestNumber"/>
        </imp1:RequestNumber>
      </xsl:if>
      <imp1:ACEDS_CONDITION-CODE>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CONDITION-CODE"/>
      </imp1:ACEDS_CONDITION-CODE>
      <imp1:ACEDS_CONDITION-DESC>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CONDITION-DESC"/>
      </imp1:ACEDS_CONDITION-DESC>
      <imp1:ACEDS_USER-ID>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_USER-ID"/>
      </imp1:ACEDS_USER-ID>
      <imp1:ACEDS_CLIENT-NUMBER-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CLIENT-NUMBER-I"/>
      </imp1:ACEDS_CLIENT-NUMBER-I>
      <imp1:ACEDS_LAST-NAME-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_LAST-NAME-I"/>
      </imp1:ACEDS_LAST-NAME-I>
      <imp1:ACEDS_FIRST-NAME-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_FIRST-NAME-I"/>
      </imp1:ACEDS_FIRST-NAME-I>
      <imp1:ACEDS_MIDDLE-NAME-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_MIDDLE-NAME-I"/>
      </imp1:ACEDS_MIDDLE-NAME-I>
      <imp1:ACEDS_SUFFIX-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_SUFFIX-I"/>
      </imp1:ACEDS_SUFFIX-I>
      <imp1:ACEDS_DATE-OF-BIRTH-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_DATE-OF-BIRTH-I"/>
      </imp1:ACEDS_DATE-OF-BIRTH-I>
      <imp1:ACEDS_SEX-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_SEX-I"/>
      </imp1:ACEDS_SEX-I>
      <imp1:ACEDS_SSN-I>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_SSN-I"/>
      </imp1:ACEDS_SSN-I>
      <imp1:ACEDS_CLIENT-SHORT-ARRAY-OUT>
        <xsl:for-each select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CLIENT-SHORT-ARRAY-OUT/string">
          <imp1:string>
            <xsl:value-of select="."/>
          </imp1:string>
        </xsl:for-each>
      </imp1:ACEDS_CLIENT-SHORT-ARRAY-OUT>
      <imp1:ACEDS_CITIZENSHIP-O>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CITIZENSHIP-O"/>
      </imp1:ACEDS_CITIZENSHIP-O>
      <imp1:ACEDS_CITIZENSHIP-VERIF-O>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CITIZENSHIP-VERIF-O"/>
      </imp1:ACEDS_CITIZENSHIP-VERIF-O>
      <imp1:ACEDS_RACE-O>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_RACE-O"/>
      </imp1:ACEDS_RACE-O>
      <imp1:ACEDS_ETHNIC-CLASS-O>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_ETHNIC-CLASS-O"/>
      </imp1:ACEDS_ETHNIC-CLASS-O>
      <imp1:ACEDS_CLIENT-NUMBER-O>
        <xsl:value-of select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CLIENT-NUMBER-O"/>
      </imp1:ACEDS_CLIENT-NUMBER-O>
      <imp1:ACEDS_MEDICAID-ARRAY>
        <xsl:for-each select="$InvokeAceds_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_MEDICAID-ARRAY/string">
          <imp1:string>
            <xsl:value-of select="."/>
          </imp1:string>
        </xsl:for-each>
      </imp1:ACEDS_MEDICAID-ARRAY>
    </imp1:ClientInquiryResponse>
  </xsl:template>
</xsl:stylesheet>
