<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeRequest.wsdl"/>
      <rootElement name="ClientInquiryRequest" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/apps/DCAS/ESB/ACEDS/wsdl/DHSDCASWebservices.wsdl"/>
      <rootElement name="DHSDQ500Response" namespace="urn:com-softwareag-entirex-rpc:EISBATCH"/>
      <param name="Client_DHSDQ500_OutputVariable.parameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/DCAS/ESB/ACEDS/wsdl/DHSDCASWebservices.wsdl"/>
      <rootElement name="DHSDQ040" namespace="urn:com-softwareag-entirex-rpc:EISBATCH"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [MON FEB 13 11:10:08 EST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://namespace.softwareag.com/entirex/xml/mapping"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:sn0="urn:com-softwareag-entirex-rpc:EISBATCH"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:snh="urn:com.softwareag.entirex.xml.rt"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_APP/HavenAcedsIncomeInquiryService/ConsumeRequest"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi ns0 xsd plt pc sn0 snh soap tns soap12 imp1 wsdl jca oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="Client_DHSDQ500_OutputVariable.parameters"/>
  <xsl:template match="/">
    <sn0:DHSDQ040>
      <_CONDITION-CODE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-CODE"/>
      </_CONDITION-CODE>
      <_CONDITION-DESC>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_CONDITION-DESC"/>
      </_CONDITION-DESC>
      <_USER-ID>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_USER-ID"/>
      </_USER-ID>
      <_CLIENT-NUMBER>
        <xsl:value-of select="$Client_DHSDQ500_OutputVariable.parameters/sn0:DHSDQ500Response/_CLIENT-NUMBER-O"/>
      </_CLIENT-NUMBER>
      <_LAST-NAME>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_LAST-NAME-I"/>
      </_LAST-NAME>
      <_FIRST-NAME>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_FIRST-NAME-I"/>
      </_FIRST-NAME>
      <_MIDDLE-NAME>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_MIDDLE-NAME-I"/>
      </_MIDDLE-NAME>
      <_SUFFIX>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SUFFIX-I"/>
      </_SUFFIX>
      <_DOB>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_DATE-OF-BIRTH-I"/>
      </_DOB>
      <_SEX>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SEX-I"/>
      </_SEX>
      <_SSN>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_SSN-I"/>
      </_SSN>
      <_INCOME-WA-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-WA-AMT"/>
      </_INCOME-WA-AMT>
      <_INCOME-WA-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-WA-TYPE"/>
      </_INCOME-WA-TYPE>
      <_INCOME-SE-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SE-AMT"/>
      </_INCOME-SE-AMT>
      <_INCOME-SE-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SE-TYPE"/>
      </_INCOME-SE-TYPE>
      <_INCOME-AL-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-AL-AMT"/>
      </_INCOME-AL-AMT>
      <_INCOME-AL-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-AL-TYPE"/>
      </_INCOME-AL-TYPE>
      <_INCOME-DV-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-DV-AMT"/>
      </_INCOME-DV-AMT>
      <_INCOME-DV-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-DV-TYPE"/>
      </_INCOME-DV-TYPE>
      <_INCOME-PE-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-PE-AMT"/>
      </_INCOME-PE-AMT>
      <_INCOME-PE-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-PE-TYPE"/>
      </_INCOME-PE-TYPE>
      <_INCOME-RO-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-RO-AMT"/>
      </_INCOME-RO-AMT>
      <_INCOME-RO-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-RO-TYPE"/>
      </_INCOME-RO-TYPE>
      <_INCOME-SS-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SS-AMT"/>
      </_INCOME-SS-AMT>
      <_INCOME-SS-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SS-TYPE"/>
      </_INCOME-SS-TYPE>
      <_INCOME-UB-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-UB-AMT"/>
      </_INCOME-UB-AMT>
      <_INCOME-UB-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-UB-TYPE"/>
      </_INCOME-UB-TYPE>
      <_INCOME-LS-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-LS-AMT"/>
      </_INCOME-LS-AMT>
      <_INCOME-LS-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-LS-TYPE"/>
      </_INCOME-LS-TYPE>
      <_INCOME-DI-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-DI-AMT"/>
      </_INCOME-DI-AMT>
      <_INCOME-DI-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-DI-TYPE"/>
      </_INCOME-DI-TYPE>
      <_INCOME-MA-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-MA-AMT"/>
      </_INCOME-MA-AMT>
      <_INCOME-MA-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-MA-TYPE"/>
      </_INCOME-MA-TYPE>
      <_INCOME-SB-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SB-AMT"/>
      </_INCOME-SB-AMT>
      <_INCOME-SB-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-SB-TYPE"/>
      </_INCOME-SB-TYPE>
      <_INCOME-PW-AMT>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-PW-AMT"/>
      </_INCOME-PW-AMT>
      <_INCOME-PW-TYPE>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-PW-TYPE"/>
      </_INCOME-PW-TYPE>
      <_INCOME-VER-FLAG>
        <xsl:value-of select="/imp1:ClientInquiryRequest/imp1:ACEDS_INCOME-VER-FLAG"/>
      </_INCOME-VER-FLAG>
    </sn0:DHSDQ040>
  </xsl:template>
</xsl:stylesheet>
