<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeRequest.wsdl"/>
      <rootElement name="ClientInquiryResponse" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/apps/DCAS/ESB/ACEDS/wsdl/DHSDCASWebservices.wsdl"/>
      <rootElement name="DHSDQ040Response" namespace="urn:com-softwareag-entirex-rpc:EISBATCH"/>
      <param name="Income_DHSDQ040_OutputVariable.parameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeRequest.wsdl"/>
      <rootElement name="ClientInquiryResponse" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [FRI FEB 17 10:02:52 EST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://namespace.softwareag.com/entirex/xml/mapping"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:sn0="urn:com-softwareag-entirex-rpc:EISBATCH"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:snh="urn:com.softwareag.entirex.xml.rt"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_APP/HavenAcedsIncomeInquiryService/ConsumeRequest"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/ACDService/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi ns0 xsd plt pc sn0 snh soap tns soap12 imp1 wsdl jca oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="Income_DHSDQ040_OutputVariable.parameters"/>
  <xsl:template match="/">
    <imp1:ClientInquiryResponse>
      <imp1:RequestNumber>
        <xsl:value-of select="/imp1:ClientInquiryResponse/imp1:RequestNumber"/>
      </imp1:RequestNumber>
      <imp1:ACEDS_CONDITION-CODE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_CONDITION-CODE"/>
      </imp1:ACEDS_CONDITION-CODE>
      <imp1:ACEDS_CONDITION-DESC>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_CONDITION-DESC"/>
      </imp1:ACEDS_CONDITION-DESC>
      <imp1:ACEDS_USER-ID>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_USER-ID"/>
      </imp1:ACEDS_USER-ID>
      <imp1:ACEDS_CLIENT-NUMBER-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_CLIENT-NUMBER"/>
      </imp1:ACEDS_CLIENT-NUMBER-I>
      <imp1:ACEDS_LAST-NAME-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_LAST-NAME"/>
      </imp1:ACEDS_LAST-NAME-I>
      <imp1:ACEDS_FIRST-NAME-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_FIRST-NAME"/>
      </imp1:ACEDS_FIRST-NAME-I>
      <imp1:ACEDS_MIDDLE-NAME-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_MIDDLE-NAME"/>
      </imp1:ACEDS_MIDDLE-NAME-I>
      <imp1:ACEDS_SUFFIX-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_SUFFIX"/>
      </imp1:ACEDS_SUFFIX-I>
      <imp1:ACEDS_DATE-OF-BIRTH-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_DOB"/>
      </imp1:ACEDS_DATE-OF-BIRTH-I>
      <imp1:ACEDS_SEX-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_SEX"/>
      </imp1:ACEDS_SEX-I>
      <imp1:ACEDS_SSN-I>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_SSN"/>
      </imp1:ACEDS_SSN-I>
      <imp1:ACEDS_INCOME-WA-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-WA-AMT"/>
      </imp1:ACEDS_INCOME-WA-AMT>
      <imp1:ACEDS_INCOME-WA-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-WA-TYPE"/>
      </imp1:ACEDS_INCOME-WA-TYPE>
      <imp1:ACEDS_INCOME-SE-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SE-AMT"/>
      </imp1:ACEDS_INCOME-SE-AMT>
      <imp1:ACEDS_INCOME-SE-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SE-TYPE"/>
      </imp1:ACEDS_INCOME-SE-TYPE>
      <imp1:ACEDS_INCOME-AL-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-AL-AMT"/>
      </imp1:ACEDS_INCOME-AL-AMT>
      <imp1:ACEDS_INCOME-AL-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-AL-TYPE"/>
      </imp1:ACEDS_INCOME-AL-TYPE>
      <imp1:ACEDS_INCOME-DV-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-DV-AMT"/>
      </imp1:ACEDS_INCOME-DV-AMT>
      <imp1:ACEDS_INCOME-DV-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-DV-TYPE"/>
      </imp1:ACEDS_INCOME-DV-TYPE>
      <imp1:ACEDS_INCOME-PE-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-PE-AMT"/>
      </imp1:ACEDS_INCOME-PE-AMT>
      <imp1:ACEDS_INCOME-PE-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-PE-TYPE"/>
      </imp1:ACEDS_INCOME-PE-TYPE>
      <imp1:ACEDS_INCOME-RO-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-RO-AMT"/>
      </imp1:ACEDS_INCOME-RO-AMT>
      <imp1:ACEDS_INCOME-RO-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-RO-TYPE"/>
      </imp1:ACEDS_INCOME-RO-TYPE>
      <imp1:ACEDS_INCOME-SS-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SS-AMT"/>
      </imp1:ACEDS_INCOME-SS-AMT>
      <imp1:ACEDS_INCOME-SS-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SS-TYPE"/>
      </imp1:ACEDS_INCOME-SS-TYPE>
      <imp1:ACEDS_INCOME-UB-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-UB-AMT"/>
      </imp1:ACEDS_INCOME-UB-AMT>
      <imp1:ACEDS_INCOME-UB-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-UB-TYPE"/>
      </imp1:ACEDS_INCOME-UB-TYPE>
      <imp1:ACEDS_INCOME-LS-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-LS-AMT"/>
      </imp1:ACEDS_INCOME-LS-AMT>
      <imp1:ACEDS_INCOME-LS-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-LS-TYPE"/>
      </imp1:ACEDS_INCOME-LS-TYPE>
      <imp1:ACEDS_INCOME-DI-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-DI-AMT"/>
      </imp1:ACEDS_INCOME-DI-AMT>
      <imp1:ACEDS_INCOME-DI-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-DI-TYPE"/>
      </imp1:ACEDS_INCOME-DI-TYPE>
      <imp1:ACEDS_INCOME-MA-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-MA-AMT"/>
      </imp1:ACEDS_INCOME-MA-AMT>
      <imp1:ACEDS_INCOME-MA-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-MA-TYPE"/>
      </imp1:ACEDS_INCOME-MA-TYPE>
      <imp1:ACEDS_INCOME-SB-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SB-AMT"/>
      </imp1:ACEDS_INCOME-SB-AMT>
      <imp1:ACEDS_INCOME-SB-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-SB-TYPE"/>
      </imp1:ACEDS_INCOME-SB-TYPE>
      <imp1:ACEDS_INCOME-PW-AMT>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-PW-AMT"/>
      </imp1:ACEDS_INCOME-PW-AMT>
      <imp1:ACEDS_INCOME-PW-TYPE>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-PW-TYPE"/>
      </imp1:ACEDS_INCOME-PW-TYPE>
      <imp1:ACEDS_INCOME-VER-FLAG>
        <xsl:value-of select="$Income_DHSDQ040_OutputVariable.parameters/sn0:DHSDQ040Response/_INCOME-VER-FLAG"/>
      </imp1:ACEDS_INCOME-VER-FLAG>
    </imp1:ClientInquiryResponse>
  </xsl:template>
</xsl:stylesheet>
