<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="GetEmploymentData" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/EmployementService/V1/"/>
    </source>
    <source type="WSDL">
      <schema location="../EmploymentServicesInfo.wsdl"/>
      <rootElement name="processResponse" namespace="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"/>
      <param name="InvokeDOES_OutputVariable.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../EmploymentServicesInfo.wsdl"/>
      <rootElement name="processResponse" namespace="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED OCT 26 16:08:46 EDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:client="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenDOESCmpService/ConsumeMessageFromJMS"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/Common/V1/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/EmployementService/V1/"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi client xsd plt pc soap plnk tns wsdl ns0 jca imp1 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="InvokeDOES_OutputVariable.payload"/>
  <xsl:template match="/">
    <client:processResponse>
      <client:ServiceStatusType>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Code">
          <client:Code>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Code"/>
          </client:Code>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Type">
          <client:Type>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Type"/>
          </client:Type>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Description">
          <client:Description>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Description"/>
          </client:Description>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:System">
          <client:System>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:System"/>
          </client:System>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:StatusDateTime">
          <client:StatusDateTime>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:StatusDateTime"/>
          </client:StatusDateTime>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Retryable">
          <client:Retryable>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Retryable/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Retryable/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:Retryable"/>
          </client:Retryable>
        </xsl:if>
        <client:ContextKey>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:ContextKey/client:ContextKeyLabel">
            <client:ContextKeyLabel>
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:ContextKey/client:ContextKeyLabel"/>
            </client:ContextKeyLabel>
          </xsl:if>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:ContextKey/client:ContextKeyValue">
            <client:ContextKeyValue>
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:ContextKey/client:ContextKeyValue"/>
            </client:ContextKeyValue>
          </xsl:if>
        </client:ContextKey>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:RawStatus">
          <client:RawStatus>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:RawStatus/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:RawStatus/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:RawStatus"/>
          </client:RawStatus>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:TransactionId">
          <client:TransactionId>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:TransactionId/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:TransactionId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:ServiceStatusType/client:TransactionId"/>
          </client:TransactionId>
        </xsl:if>
      </client:ServiceStatusType>
      <client:EmploymentServicesData>
        <client:BenefitWeeksRemain>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitWeeksRemain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitWeeksRemain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitWeeksRemain"/>
        </client:BenefitWeeksRemain>
        <client:BenefitsToDate>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsToDate/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsToDate/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsToDate"/>
        </client:BenefitsToDate>
        <client:ClaimantID>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ClaimantID"/>
        </client:ClaimantID>
        <client:ApplicantState>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ApplicantState/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ApplicantState/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ApplicantState"/>
        </client:ApplicantState>
        <client:ApplicantFirstName>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ApplicantFirstName"/>
        </client:ApplicantFirstName>
        <client:ApplicantLastName>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:ApplicantLastName"/>
        </client:ApplicantLastName>
        <client:LastEmployer>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:LastEmployer"/>
        </client:LastEmployer>
        <client:LastEmployerEIN>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:LastEmployerEIN"/>
        </client:LastEmployerEIN>
        <client:LastEmploymentWages>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:LastEmploymentWages"/>
        </client:LastEmploymentWages>
        <client:LastPaymentDate>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:LastPaymentDate"/>
        </client:LastPaymentDate>
        <client:LengthLastEmployed>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:LengthLastEmployed"/>
        </client:LengthLastEmployed>
        <client:MaxBenefitAllowance>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:MaxBenefitAllowance/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:MaxBenefitAllowance/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:MaxBenefitAllowance"/>
        </client:MaxBenefitAllowance>
        <client:PartialPaymentAmount>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PartialPaymentAmount/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PartialPaymentAmount/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PartialPaymentAmount"/>
        </client:PartialPaymentAmount>
        <client:PaymentAmount>
          <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentAmount/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentAmount/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentAmount"/>
        </client:PaymentAmount>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsFrequency">
          <client:BenefitsFrequency>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsFrequency/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsFrequency/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:BenefitsFrequency"/>
          </client:BenefitsFrequency>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentsFrequency">
          <client:PaymentsFrequency>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentsFrequency/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentsFrequency/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:PaymentsFrequency"/>
          </client:PaymentsFrequency>
        </xsl:if>
        <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:IsEmployed">
          <client:IsEmployed>
            <xsl:if test="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:IsEmployed/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:IsEmployed/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InvokeDOES_OutputVariable.payload/client:processResponse/client:EmploymentServicesData/client:IsEmployed"/>
          </client:IsEmployed>
        </xsl:if>
      </client:EmploymentServicesData>
      <client:RequestNumber>
        <xsl:value-of select="/imp1:GetEmploymentData/imp1:RequestNumber"/>
      </client:RequestNumber>
    </client:processResponse>
  </xsl:template>
</xsl:stylesheet>
