<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="GetEmploymentData" namespace="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/EmployementService/V1/"/>
    </source>
    <source type="WSDL">
      <schema location="../EmploymentServicesInfo.wsdl"/>
      <rootElement name="processResponse" namespace="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"/>
      <param name="InvokeDOES_OutputVariable.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../EmploymentServicesInfo.wsdl"/>
      <rootElement name="processResponse" namespace="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED JUL 26 17:14:06 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:client="http://xmlns.oracle.com/DCASLocalHub/EmploymentServicesInfo/EmploymentServicesInfoBPEL"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenDOESCmpService/ConsumeMessageFromJMS"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/Common/V1/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://xmlns.dhs.dc.gov/DCAS/ESB/Local/EmployementService/V1/"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi client xsd plt pc soap plnk tns wsdl ns0 jca imp1 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="InvokeDOES_OutputVariable.payload"/>
  <xsl:template match="/">
    <client:processResponse>
      <client:ServiceStatusType>
        <client:Code>
          <xsl:text disable-output-escaping="no">000</xsl:text>
        </client:Code>
        <client:Type>
          <xsl:text disable-output-escaping="no">Success</xsl:text>
        </client:Type>
        <client:Description>
          <xsl:text disable-output-escaping="no">Success</xsl:text>
        </client:Description>
        <client:ContextKey>
          <client:ContextKeyLabel>
            <xsl:text disable-output-escaping="no">DCAS - DOES - EmploymentService - SSN</xsl:text>
          </client:ContextKeyLabel>
          <client:ContextKeyValue>
            <xsl:text disable-output-escaping="no">HX114</xsl:text>
          </client:ContextKeyValue>
        </client:ContextKey>
      </client:ServiceStatusType>
      <client:EmploymentServicesData>
        <client:BenefitWeeksRemain>
          <xsl:text disable-output-escaping="no">14</xsl:text>
        </client:BenefitWeeksRemain>
        <client:ApplicantState>
          <xsl:text disable-output-escaping="no">DC</xsl:text>
        </client:ApplicantState>
        <client:ApplicantFirstName>
          <xsl:text disable-output-escaping="no">Test</xsl:text>
        </client:ApplicantFirstName>
        <client:ApplicantLastName>
          <xsl:text disable-output-escaping="no">Four</xsl:text>
        </client:ApplicantLastName>
        <client:LastEmployer>
          <xsl:text disable-output-escaping="no">XYZ LLC.</xsl:text>
        </client:LastEmployer>
         <client:LastEmployerEIN>
          <xsl:text disable-output-escaping="no">123456789</xsl:text>
        </client:LastEmployerEIN>
        <client:LastEmploymentWages>
          <xsl:text disable-output-escaping="no">1105.50</xsl:text>
        </client:LastEmploymentWages>
        <client:LastPaymentDate>
          <xsl:text disable-output-escaping="no">2017-07-01</xsl:text>
        </client:LastPaymentDate>
        <client:LengthLastEmployed>
          <xsl:text disable-output-escaping="no">13</xsl:text>
        </client:LengthLastEmployed>
        <client:MaxBenefitAllowance>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </client:MaxBenefitAllowance>
        <client:PartialPaymentAmount>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </client:PartialPaymentAmount>
        <client:PaymentAmount>
          <xsl:text disable-output-escaping="no">1105.5</xsl:text>
        </client:PaymentAmount>
        <client:BenefitsFrequency>
          <xsl:text disable-output-escaping="no">Monthly</xsl:text>
        </client:BenefitsFrequency>
        <client:PaymentsFrequency>
          <xsl:text disable-output-escaping="no">Monthly</xsl:text>
        </client:PaymentsFrequency>
        <client:IsEmployed>
          <xsl:text disable-output-escaping="no">true</xsl:text>
        </client:IsEmployed>
      </client:EmploymentServicesData>
      <client:RequestNumber>
        <xsl:value-of select="/imp1:GetEmploymentData/imp1:RequestNumber"/>
      </client:RequestNumber>
    </client:processResponse>
  </xsl:template>
</xsl:stylesheet>
