<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HavenIsResidentABCSImpl.wsdl"/>
      <rootElement name="is_resident_evidence" namespace=""/>
    </source>
    <source type="WSDL">
      <schema location="../IsResidentPull.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentPull"/>
      <param name="IsResidentPull_OutputVariable.OutputParameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HavenIsResidentABCSImpl.wsdl"/>
      <rootElement name="is_resident_evidences" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentRespService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [FRI OCT 13 10:08:51 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:db1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentRespService"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentReqService"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:client="http://xmlns.oracle.com/Test/HavenIsResidentCmpService/HavenIsResidentABCSImpl"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentPull"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Haven/HavenIsResidentService/IsResidentPull"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi db1 db xsd plt client ns0 soap plnk tns ns1 wsdl oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="IsResidentPull_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <db1:is_resident_evidences>
      <db1:ResponseCode>
        <xsl:value-of select="$IsResidentPull_OutputVariable.OutputParameters/ns0:OutputParameters/ns0:O_RESPONSE_CODE"/>
      </db1:ResponseCode>
      <db1:ResponseText>
        <xsl:value-of select="$IsResidentPull_OutputVariable.OutputParameters/ns0:OutputParameters/ns0:O_RESPONSE_TEXT"/>
      </db1:ResponseText>
      <db1:is_resident_evidence>
        <db1:filer_IC>
          <xsl:value-of select="/is_resident_evidence/filer_IC"/>
        </db1:filer_IC>
        <db1:is_resident>
          <xsl:value-of select="/is_resident_evidence/is_resident"/>
        </db1:is_resident>
        <db1:residenceReason>
          <xsl:value-of select="/is_resident_evidence/residenceReason"/>
        </db1:residenceReason>
        <db1:startDate>
          <xsl:value-of select="/is_resident_evidence/startDate"/>
        </db1:startDate>
        <db1:endDate>
          <xsl:value-of select="/is_resident_evidence/endDate"/>
        </db1:endDate>
        <db1:temporaryAbsence>
          <xsl:value-of select="/is_resident_evidence/temporaryAbsence"/>
        </db1:temporaryAbsence>
        <db1:comments>
          <xsl:value-of select="/is_resident_evidence/comments"/>
        </db1:comments>
        <db1:caseParticipantRoleID>
          <xsl:value-of select="/is_resident_evidence/caseParticipantRoleID"/>
        </db1:caseParticipantRoleID>
        <db1:participantID>
          <xsl:value-of select="/is_resident_evidence/participantID"/>
        </db1:participantID>
        <db1:evidenceID>
          <xsl:value-of select="/is_resident_evidence/evidenceID"/>
        </db1:evidenceID>
      </db1:is_resident_evidence>
    </db1:is_resident_evidences>
  </xsl:template>
</xsl:stylesheet>
