<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="HavenTaxDepABCSImpl"
                  targetNamespace="http://xmlns.oracle.com/Test/HavenTaxDepCmpService/HavenTaxDepABCSImpl"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:client="http://xmlns.oracle.com/Test/HavenTaxDepCmpService/HavenTaxDepABCSImpl"
                  xmlns:ns2="http://xmlns.haven.dc.govcom/haven/taxdepdetailsout"
                  xmlns:ns1="http://xmlns.haven.dc.govcom/haven/taxdepdetailsin"
                  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <plnk:partnerLinkType name="HavenTaxDepABCSImpl">
      <plnk:role name="HavenTaxDepABCSImplProvider"
                 portType="client:HavenTaxDepABCSImpl"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema"
              xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
              xmlns:client="http://xmlns.oracle.com/Test/HavenTaxDepCmpService/HavenTaxDepABCSImpl"
              xmlns:ns2="http://xmlns.haven.dc.govcom/haven/taxdepdetailsout"
              xmlns:ns1="http://xmlns.haven.dc.govcom/haven/taxdepdetailsin"
              xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
         <import namespace="http://xmlns.haven.dc.govcom/haven/taxdepdetailsin"
                 schemaLocation="xsd/taxdepsin.xsd"/>
         <import namespace="http://xmlns.haven.dc.govcom/haven/taxdepdetailsout"
                 schemaLocation="xsd/taxdepsout.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:include schemaLocation="xsd/TaxDependentSP_sp.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="HavenTaxDepABCSImplRequestMessage">
      <wsdl:part name="payload" element="ns1:TaxDep_InputParameters"/>
   </wsdl:message>
   <wsdl:message name="HavenTaxDepABCSImplResponseMessage">
      <wsdl:part name="payload" element="ns2:tax_dep_Response"/>
   </wsdl:message>
   <wsdl:portType name="HavenTaxDepABCSImpl">
      <wsdl:operation name="TaxDependents">
         <wsdl:input message="client:HavenTaxDepABCSImplRequestMessage"/>
         <wsdl:output message="client:HavenTaxDepABCSImplResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="HavenTaxDepABCSImplSOAP11Binding"
                 type="client:HavenTaxDepABCSImpl">
      <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="TaxDependents">
         <soap:operation style="document"
                         soapAction="http://xmlns.oracle.com/Test/HavenTaxDepCmpService/HavenTaxDepABCSImpl/TaxDependents"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
