<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HavenIsResidentABCSImpl"
     targetNamespace="http://xmlns.oracle.com/HavenAppCaseRefService/HavenAppCaseRefABCSImpl"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:client="http://xmlns.oracle.com/HavenAppCaseRefService/HavenAppCaseRefABCSImpl"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    >
    <plnk:partnerLinkType name="HavenAppRefService">
        <plnk:role name="HavenAppRefABCSImpl" portType="client:HavenAppRefABCSImpl"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/HavenAppCaseRefService/HavenAppCaseRefABCSImpl"
         location="HavenAppCaseRefABCSImpl.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:include schemaLocation="xsd/AppCase_sp_format.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
