<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HavenDeductionsABCSImpl.wsdl"/>
      <rootElement name="deductions" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsService"/>
    </source>
    <source type="WSDL">
      <schema location="../DeductionsSP.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsSP"/>
      <param name="DeductionsSP_OutputVariable.OutputParameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HavenDeductionsABCSImpl.wsdl"/>
      <rootElement name="deductions" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU OCT 05 10:11:09 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:client="http://xmlns.oracle.com/Test/DeductionsService/DeductionsServiceABCSImpl"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Haven/HavenDeductionsService/DeductionsSP"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsSP"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsService"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi client xsd plt soap plnk tns ns1 wsdl ns0 db oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="DeductionsSP_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <db:deductions>
      <db:ResponseCode>
        <xsl:value-of select="$DeductionsSP_OutputVariable.OutputParameters/ns0:OutputParameters/ns0:O_RESPONSE_CODE"/>
      </db:ResponseCode>
      <db:ResponseText>
        <xsl:value-of select="$DeductionsSP_OutputVariable.OutputParameters/ns0:OutputParameters/ns0:O_RESPONSE_TEXT"/>
      </db:ResponseText>
      <db:deduction>
        <db:evidenceID>
          <xsl:value-of select="/db:deductions/db:deduction/db:evidenceID"/>
        </db:evidenceID>
        <db:deduction_typeCode>
          <xsl:value-of select="/db:deductions/db:deduction/db:deduction_typeCode"/>
        </db:deduction_typeCode>
        <db:income_type>
          <xsl:value-of select="/db:deductions/db:deduction/db:income_type"/>
        </db:income_type>
        <db:amount>
          <xsl:value-of select="/db:deductions/db:deduction/db:amount"/>
        </db:amount>
        <db:ded_frequencyCode>
          <xsl:value-of select="/db:deductions/db:deduction/db:ded_frequencyCode"/>
        </db:ded_frequencyCode>
        <db:frequency>
          <xsl:value-of select="/db:deductions/db:deduction/db:frequency"/>
        </db:frequency>
        <db:start_date>
          <xsl:value-of select="/db:deductions/db:deduction/db:start_date"/>
        </db:start_date>
        <db:end_date>
          <xsl:value-of select="/db:deductions/db:deduction/db:end_date"/>
        </db:end_date>
        <db:ded_caseParticipantRoleID>
          <xsl:value-of select="/db:deductions/db:deduction/db:ded_caseParticipantRoleID"/>
        </db:ded_caseParticipantRoleID>
        <db:ded_ParticipantRoleID>
          <xsl:value-of select="/db:deductions/db:deduction/db:ded_ParticipantRoleID"/>
        </db:ded_ParticipantRoleID>
        <db:statuscode>
          <xsl:value-of select="/db:deductions/db:deduction/db:statuscode"/>
        </db:statuscode>
        <db:receiveddate>
          <xsl:value-of select="/db:deductions/db:deduction/db:receiveddate"/>
        </db:receiveddate>
        <db:correctionsetid>
          <xsl:value-of select="/db:deductions/db:deduction/db:correctionsetid"/>
        </db:correctionsetid>
      </db:deduction>
    </db:deductions>
  </xsl:template>
</xsl:stylesheet>
