<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../DeductionsSP.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsSP"/>
    </source>
    <source type="WSDL">
      <schema location="../DeductionsSP.wsdl"/>
      <rootElement name="deductions" namespace=""/>
      <param name="FormatResp" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HavenDeductionsABCSImpl.wsdl"/>
      <rootElement name="deductions" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU OCT 05 10:11:27 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:client="http://xmlns.oracle.com/Test/DeductionsService/DeductionsServiceABCSImpl"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Haven/HavenDeductionsService/DeductionsSP"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsSP"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DeductionsService"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi xsd plt tns ns1 wsdl db client soap plnk ns0 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="FormatResp"/>
  <xsl:template match="/">
    <ns0:deductions>
      <ns0:ResponseCode>
        <xsl:value-of select="/db:OutputParameters/db:O_RESPONSE_CODE"/>
      </ns0:ResponseCode>
      <ns0:ResponseText>
        <xsl:value-of select="/db:OutputParameters/db:O_RESPONSE_TEXT"/>
      </ns0:ResponseText>
      <xsl:for-each select="$FormatResp/deductions/deduction">
        <ns0:deduction>
          <ns0:evidenceID>
            <xsl:value-of select="evidenceID"/>
          </ns0:evidenceID>
          <ns0:deduction_typeCode>
            <xsl:value-of select="deduction_typeCode"/>
          </ns0:deduction_typeCode>
          <ns0:income_type>
            <xsl:value-of select="income_type"/>
          </ns0:income_type>
          <ns0:amount>
            <xsl:value-of select="amount"/>
          </ns0:amount>
          <ns0:ded_frequencyCode>
            <xsl:value-of select="ded_frequencyCode"/>
          </ns0:ded_frequencyCode>
          <ns0:frequency>
            <xsl:value-of select="frequency"/>
          </ns0:frequency>
          <ns0:start_date>
            <xsl:value-of select="start_date"/>
          </ns0:start_date>
          <ns0:end_date>
            <xsl:value-of select="end_date"/>
          </ns0:end_date>
          <ns0:ded_caseParticipantRoleID>
            <xsl:value-of select="ded_caseParticipantRoleID"/>
          </ns0:ded_caseParticipantRoleID>
          <ns0:ded_ParticipantRoleID>
            <xsl:value-of select="ded_ParticipantRoleID"/>
          </ns0:ded_ParticipantRoleID>
          <ns0:statuscode>
            <xsl:value-of select="statuscode"/>
          </ns0:statuscode>
          <ns0:receiveddate>
            <xsl:value-of select="receiveddate"/>
          </ns0:receiveddate>
          <ns0:correctionsetid>
            <xsl:value-of select="correctionsetid"/>
          </ns0:correctionsetid>
        </ns0:deduction>
      </xsl:for-each>
    </ns0:deductions>
  </xsl:template>
</xsl:stylesheet>
