<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../TaxDepsdb.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TaxDepsdb"/>
    </source>
    <source type="WSDL">
      <schema location="../HavenTaxDepABCSImpl.wsdl"/>
      <rootElement name="tax_dep_details" namespace=""/>
      <param name="Format_SP" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HavenTaxDepABCSImpl.wsdl"/>
      <rootElement name="tax_dep_Response" namespace="http://xmlns.haven.dc.govcom/haven/taxdepdetailsout"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [FRI SEP 29 14:10:44 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Test/HavenTaxDepCmpService/TaxDepsdb"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.haven.dc.govcom/haven/taxdepdetailsin"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://xmlns.haven.dc.govcom/haven/taxdepdetailsout"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TaxDepsdb"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:client="http://xmlns.oracle.com/Test/HavenTaxDepCmpService/HavenTaxDepABCSImpl"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi tns xsd plt ns1 ns2 db soap plnk wsdl client oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="Format_SP"/>
  <xsl:template match="/">
    <ns2:tax_dep_Response>
      <ns2:ResponseCode>
        <xsl:value-of select="/db:OutputParameters/db:O_RESPONSE_CODE"/>
      </ns2:ResponseCode>
      <ns2:ResponseText>
        <xsl:value-of select="/db:OutputParameters/db:O_RESPONSE_TEXT"/>
      </ns2:ResponseText>
      <ns2:tax_dep_details>
        <ns2:tfs_evidenceID>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_evidenceID"/>
        </ns2:tfs_evidenceID>
        <ns2:tfs_taxFilingStatus>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_taxFilingStatus"/>
        </ns2:tfs_taxFilingStatus>
        <ns2:First_Name>
          <xsl:value-of select="$Format_SP/tax_dep_details/First_Name"/>
        </ns2:First_Name>
        <ns2:Last_Name>
          <xsl:value-of select="$Format_SP/tax_dep_details/Last_Name"/>
        </ns2:Last_Name>
        <ns2:Dob>
          <xsl:value-of select="$Format_SP/tax_dep_details/Dob"/>
        </ns2:Dob>
        <ns2:tfs_taxFilingTogether>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_taxFilingTogether"/>
        </ns2:tfs_taxFilingTogether>
        <ns2:tfs_isClaimedAsDeOfExtPerson>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_isClaimedAsDeOfExtPerson"/>
        </ns2:tfs_isClaimedAsDeOfExtPerson>
        <ns2:tfs_startDate>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_startDate"/>
        </ns2:tfs_startDate>
        <ns2:tfs_endDate>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_endDate"/>
        </ns2:tfs_endDate>
        <ns2:tfs_caseParticipantRoleID>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_caseParticipantRoleID"/>
        </ns2:tfs_caseParticipantRoleID>
        <ns2:tfs_ParticipantRoleID>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_ParticipantRoleID"/>
        </ns2:tfs_ParticipantRoleID>
        <ns2:tfs_comments>
          <xsl:value-of select="$Format_SP/tax_dep_details/tfs_comments"/>
        </ns2:tfs_comments>
        <ns2:tax_dependents>
          <xsl:for-each select="$Format_SP/tax_dep_details/tax_dependents/tax_dependent">
            <ns2:tax_dependent>
              <xsl:value-of select="."/>
            </ns2:tax_dependent>
          </xsl:for-each>
        </ns2:tax_dependents>
      </ns2:tax_dep_details>
    </ns2:tax_dep_Response>
  </xsl:template>
</xsl:stylesheet>
