<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HavenAppCaseRefABCSImplWrapper.wsdl"/>
      <rootElement name="AppCaseRefFromIC" namespace=""/>
    </source>
    <source type="WSDL">
      <schema location="../AppCaseRefPull.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AppCaseRefPull"/>
      <param name="AppCaseRefPull_OutputVariable.OutputParameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HavenAppCaseRefABCSImpl.wsdl"/>
      <rootElement name="AppRefOutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AppCaseRespService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [FRI OCT 13 11:02:06 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:db1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentRespService"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/IsResidentReqService"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:client="http://xmlns.oracle.com/HavenAppCaseRefService/HavenAppCaseRefABCSImpl"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AppCaseReqService"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Haven/HavenAppCaseRefService/AppCaseRefPull"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AppCaseRefPull"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AppCaseRespService"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi xsd plt client soap plnk tns wsdl db bpel db1 ns0 ns2 ns1 ns3 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="AppCaseRefPull_OutputVariable.OutputParameters"/>
  <xsl:template match="/">
    <ns3:AppRefOutputParameters>
      <ns3:ResponseCode>
        <xsl:value-of select="$AppCaseRefPull_OutputVariable.OutputParameters/db:OutputParameters/db:O_RESPONSE_CODE"/>
      </ns3:ResponseCode>
      <ns3:ResponseText>
        <xsl:value-of select="$AppCaseRefPull_OutputVariable.OutputParameters/db:OutputParameters/db:O_RESPONSE_TEXT"/>
      </ns3:ResponseText>
      <ns3:AppCaseRefFromIC>
        <ns3:IntegratedCase_ID>
          <xsl:value-of select="/AppCaseRefFromIC/IntegratedCase_ID"/>
        </ns3:IntegratedCase_ID>
        <ns3:AppCaseRef>
          <xsl:value-of select="/AppCaseRefFromIC/AppCaseRef"/>
        </ns3:AppCaseRef>
      </ns3:AppCaseRefFromIC>
    </ns3:AppRefOutputParameters>
  </xsl:template>
</xsl:stylesheet>
