<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ICReferenceCasePollSvc.wsdl"/>
      <rootElement name="DchxeaiccaserefCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ICReferenceCasePollSvc"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ICRefNumPublishSvc.wsdl"/>
      <rootElement name="Request" namespace="http://CRMIntegrationACAPi/terms/1.0"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [FRI AUG 11 10:52:06 EDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ICReferenceCasePollSvc"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DCAPP/CuramEAIntegrationSvc/ICReferenceCasePollSvc"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/jms/DCAPP/CuramEAIntegrationSvc/ICRefNumPublishSvc"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:imp1="http://CRMIntegrationACAPi/terms/1.0"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi top tns xsd plt ns1 wsdl ns0 imp1 jca oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <imp1:Request>
      <imp1:IntegratedCase_ID>
        <xsl:value-of select="/top:DchxeaiccaserefCollection/top:Dchxeaiccaseref/top:iccasereference"/>
      </imp1:IntegratedCase_ID>
    </imp1:Request>
  </xsl:template>
</xsl:stylesheet>
