<?xml version='1.0' encoding='UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns2="https://openhbx.gov/haven/insurancedetails/response" xmlns:ns1="https://openhbx.gov/haven/insurancedetails/request" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns3="https://openhbx.gov/haven/insurancedetails/spfomrat" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/InsDetailsSP" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:client="http://xmlns.oracle.com/Test/HavenInsuranceDetailsCmpService/HavenInsuranceDetailsABCSImpl" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Test/HavenInsuranceDetailsCmpService/InsDetailsSP" exclude-result-prefixes="xsl xsi ns2 ns1 xsd ns3 plnk wsdl client plt db tns oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
   <xsl:template match="/">
      <db:InputParameters>
         <db:I_CONCERNROLEID>
            <xsl:value-of select="/ns1:InsurnaceInput/ns1:I_CONCERNROLEID"/>
         </db:I_CONCERNROLEID>
      </db:InputParameters>
   </xsl:template>
</xsl:stylesheet>
