<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeESIMECRequest.wsdl"/>
      <rootElement name="ESIMECRequest" namespace="http://vesim.dsh.cms.gov/exchange/1.0"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeESIMECRequest.wsdl"/>
      <rootElement name="ESIMECRequest" namespace="http://vesim.dsh.cms.gov/exchange/1.0"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE OCT 18 11:33:31 EDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://hix.cms.gov/0.1/hix-core"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns3="http://niem.gov/niem/niem-core/2.0"
                xmlns:ns4="http://niem.gov/niem/appinfo/2.1"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns5="http://niem.gov/niem/appinfo/2.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns6="http://niem.gov/niem/structures/2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns7="http://niem.gov/niem/usps_states/2.0"
                xmlns:ns0="http://niem.gov/niem/fbi/2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns2="http://vesim.dsh.cms.gov/extension/1.0"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_APP/HavenESIMEConsumeService/ConsumeESIMECRequest"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://vesim.dsh.cms.gov/exchange/1.0"
                xmlns:ns8="http://hix.cms.gov/0.1/hix-ee"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ns9="http://niem.gov/niem/proxy/xsd/2.0"
                exclude-result-prefixes="xsl xsi ns1 xsd plt ns3 ns4 pc ns5 ns6 ns7 ns0 ns2 tns wsdl jca imp1 ns8 ns9 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <imp1:ESIMECRequest>
      <xsl:for-each select="/imp1:ESIMECRequest/ns2:ApplicantRequest">
        <ns2:ApplicantRequest>
          <ns2:RequestPerson>
            <ns3:PersonBirthDate>
              <xsl:if test="ns2:RequestPerson/ns3:PersonBirthDate/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ns2:RequestPerson/ns3:PersonBirthDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <ns3:Date>
                <xsl:if test="ns2:RequestPerson/ns3:PersonBirthDate/ns3:Date/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:RequestPerson/ns3:PersonBirthDate/ns3:Date/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns2:RequestPerson/ns3:PersonBirthDate/ns3:Date"/>
              </ns3:Date>
            </ns3:PersonBirthDate>
            <ns3:PersonName>
              <ns3:PersonGivenName>
                <xsl:if test="ns2:RequestPerson/ns3:PersonName/ns3:PersonGivenName/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonGivenName/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonGivenName"/>
              </ns3:PersonGivenName>
              <xsl:if test='ns2:RequestPerson/ns3:PersonName/ns3:PersonMiddleName != ""'>
                <ns3:PersonMiddleName>
                  <xsl:if test="ns2:RequestPerson/ns3:PersonName/ns3:PersonMiddleName/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonMiddleName/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonMiddleName"/>
                </ns3:PersonMiddleName>
              </xsl:if>
              <ns3:PersonSurName>
                <xsl:if test="ns2:RequestPerson/ns3:PersonName/ns3:PersonSurName/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonSurName/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonSurName"/>
              </ns3:PersonSurName>
              <xsl:if test="ns2:RequestPerson/ns3:PersonName/ns3:PersonNameSuffixText">
                <ns3:PersonNameSuffixText>
                  <xsl:if test="ns2:RequestPerson/ns3:PersonName/ns3:PersonNameSuffixText/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonNameSuffixText/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns2:RequestPerson/ns3:PersonName/ns3:PersonNameSuffixText"/>
                </ns3:PersonNameSuffixText>
              </xsl:if>
            </ns3:PersonName>
            <xsl:if test="ns2:RequestPerson/ns3:PersonSexCode">
              <ns3:PersonSexCode>
                <xsl:if test="ns2:RequestPerson/ns3:PersonSexCode/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:RequestPerson/ns3:PersonSexCode/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns2:RequestPerson/ns3:PersonSexCode"/>
              </ns3:PersonSexCode>
            </xsl:if>
            <ns3:PersonSSNIdentification>
              <xsl:if test="ns2:RequestPerson/ns3:PersonSSNIdentification/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ns2:RequestPerson/ns3:PersonSSNIdentification/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns2:RequestPerson/ns3:PersonSSNIdentification/ns3:IdentificationID">
                <xsl:for-each select="ns2:RequestPerson/ns3:PersonSSNIdentification/ns3:IdentificationID">
                  <ns3:IdentificationID>
                    <xsl:if test="@xsi:nil">
                      <xsl:attribute name="xsi:nil">
                        <xsl:value-of select="@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="."/>
                  </ns3:IdentificationID>
                </xsl:for-each>
              </xsl:if>
            </ns3:PersonSSNIdentification>
          </ns2:RequestPerson>
          <ns2:InsuranceApplicantRequest>
            <ns8:InsuranceApplicantRequestedCoverage>
              <ns3:StartDate>
                <xsl:if test="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <ns3:Date>
                  <xsl:if test="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date"/>
                </ns3:Date>
              </ns3:StartDate>
              <ns3:EndDate>
                <xsl:if test="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <ns3:Date>
                  <xsl:if test="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns2:InsuranceApplicantRequest/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date"/>
                </ns3:Date>
              </ns3:EndDate>
            </ns8:InsuranceApplicantRequestedCoverage>
          </ns2:InsuranceApplicantRequest>
          <ns2:PersonLocationState>
            <xsl:value-of select="ns2:PersonLocationState"/>
          </ns2:PersonLocationState>
        </ns2:ApplicantRequest>
      </xsl:for-each>
    </imp1:ESIMECRequest>
  </xsl:template>
</xsl:stylesheet>
