<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeESIMECRequest.wsdl"/>
      <rootElement name="ESIMECResponse" namespace="http://vesim.dsh.cms.gov/exchange/1.0"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeESIMECRequest.wsdl"/>
      <rootElement name="ESIMECResponse" namespace="http://vesim.dsh.cms.gov/exchange/1.0"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED OCT 26 17:30:49 EDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://hix.cms.gov/0.1/hix-core"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns3="http://niem.gov/niem/niem-core/2.0"
                xmlns:ns4="http://niem.gov/niem/appinfo/2.1"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns5="http://niem.gov/niem/appinfo/2.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns6="http://niem.gov/niem/structures/2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns7="http://niem.gov/niem/usps_states/2.0"
                xmlns:ns0="http://niem.gov/niem/fbi/2.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns2="http://vesim.dsh.cms.gov/extension/1.0"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_APP/HavenESIMEConsumeService/ConsumeESIMECRequest"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://vesim.dsh.cms.gov/exchange/1.0"
                xmlns:ns8="http://hix.cms.gov/0.1/hix-ee"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ns9="http://niem.gov/niem/proxy/xsd/2.0"
                exclude-result-prefixes="xsl xsi ns1 xsd plt ns3 ns4 pc ns5 ns6 ns7 ns0 ns2 tns wsdl jca imp1 ns8 ns9 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <imp1:ESIMECResponse>
      <ns2:ResponseMetadata>
        <ns1:ResponseCode>
          <xsl:value-of select="/imp1:ESIMECResponse/ns2:ResponseMetadata/ns1:ResponseCode"/>
        </ns1:ResponseCode>
        <ns1:ResponseDescriptionText>
          <xsl:value-of select="/imp1:ESIMECResponse/ns2:ResponseMetadata/ns1:ResponseDescriptionText"/>
        </ns1:ResponseDescriptionText>
      </ns2:ResponseMetadata>
      <ns2:ApplicantResponseSet>
        <xsl:for-each select="/imp1:ESIMECResponse/ns2:ApplicantResponseSet/ns2:ApplicantResponse">
          <ns2:ApplicantResponse>
            <ns2:ResponsePerson>
              <ns3:PersonSSNIdentification>
                <xsl:if test="ns2:ResponsePerson/ns3:PersonSSNIdentification/@xsi:nil">
                  <xsl:attribute name="xsi:nil">
                    <xsl:value-of select="ns2:ResponsePerson/ns3:PersonSSNIdentification/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns2:ResponsePerson/ns3:PersonSSNIdentification/ns3:IdentificationID">
                  <xsl:for-each select="ns2:ResponsePerson/ns3:PersonSSNIdentification/ns3:IdentificationID">
                    <ns3:IdentificationID>
                      <xsl:if test="@xsi:nil">
                        <xsl:attribute name="xsi:nil">
                          <xsl:value-of select="@xsi:nil"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="."/>
                    </ns3:IdentificationID>
                  </xsl:for-each>
                </xsl:if>
              </ns3:PersonSSNIdentification>
            </ns2:ResponsePerson>
            <ns1:ResponseMetadata>
              <ns1:ResponseCode>
                <xsl:value-of select="ns1:ResponseMetadata/ns1:ResponseCode"/>
              </ns1:ResponseCode>
              <ns1:ResponseDescriptionText>
                <xsl:value-of select="ns1:ResponseMetadata/ns1:ResponseDescriptionText"/>
              </ns1:ResponseDescriptionText>
            </ns1:ResponseMetadata>
            <xsl:if test="ns2:ApplicantMECInformation">
              <ns2:ApplicantMECInformation>
                <ns2:InsuranceApplicantResponse>
                  <ns8:InsuranceApplicantRequestedCoverage>
                    <ns3:StartDate>
                      <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/@xsi:nil">
                        <xsl:attribute name="xsi:nil">
                          <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/@xsi:nil"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns3:Date>
                        <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:StartDate/ns3:Date"/>
                      </ns3:Date>
                    </ns3:StartDate>
                    <ns3:EndDate>
                      <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/@xsi:nil">
                        <xsl:attribute name="xsi:nil">
                          <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/@xsi:nil"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns3:Date>
                        <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantRequestedCoverage/ns3:EndDate/ns3:Date"/>
                      </ns3:Date>
                    </ns3:EndDate>
                  </ns8:InsuranceApplicantRequestedCoverage>
                  <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantEligibleEmployerSponsoredInsuranceIndicator">
                    <ns8:InsuranceApplicantEligibleEmployerSponsoredInsuranceIndicator>
                      <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantEligibleEmployerSponsoredInsuranceIndicator"/>
                    </ns8:InsuranceApplicantEligibleEmployerSponsoredInsuranceIndicator>
                  </xsl:if>
                  <xsl:if test="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantInsuredIndicator">
                    <ns8:InsuranceApplicantInsuredIndicator>
                      <xsl:value-of select="ns2:ApplicantMECInformation/ns2:InsuranceApplicantResponse/ns8:InsuranceApplicantInsuredIndicator"/>
                    </ns8:InsuranceApplicantInsuredIndicator>
                  </xsl:if>
                </ns2:InsuranceApplicantResponse>
                <ns1:InconsistencyIndicator>
                  <xsl:value-of select="ns2:ApplicantMECInformation/ns1:InconsistencyIndicator"/>
                </ns1:InconsistencyIndicator>
                <xsl:if test="ns2:ApplicantMECInformation/ns2:MonthlyPremiumAmount">
                  <ns2:MonthlyPremiumAmount>
                    <ns2:EmployeePremiumAmount>
                      <ns8:InsurancePremiumAmount>
                        <xsl:value-of select="ns2:ApplicantMECInformation/ns2:MonthlyPremiumAmount/ns2:EmployeePremiumAmount/ns8:InsurancePremiumAmount"/>
                      </ns8:InsurancePremiumAmount>
                    </ns2:EmployeePremiumAmount>
                    <ns2:FamilyPremiumAmount>
                      <ns8:InsurancePremiumAmount>
                        <xsl:value-of select="ns2:ApplicantMECInformation/ns2:MonthlyPremiumAmount/ns2:FamilyPremiumAmount/ns8:InsurancePremiumAmount"/>
                      </ns8:InsurancePremiumAmount>
                    </ns2:FamilyPremiumAmount>
                  </ns2:MonthlyPremiumAmount>
                </xsl:if>
              </ns2:ApplicantMECInformation>
            </xsl:if>
          </ns2:ApplicantResponse>
        </xsl:for-each>
      </ns2:ApplicantResponseSet>
      <imp1:RequestNumber>
        <xsl:value-of select="/imp1:ESIMECResponse/imp1:RequestNumber"/>
      </imp1:RequestNumber>
    </imp1:ESIMECResponse>
  </xsl:template>
</xsl:stylesheet>
